### ISSUE TITLE
backdoor found

### ISSUE THREAD

**Issue by jskimm** [safflower/safflower.py#4]
backdoor found in safflower module

**Comment by seonggwonyoon** [comment]
I agree

**Comment by gomsoup** [comment]
reported

**Comment by pengsaff** [comment]
solved. thanks everyone.

**Comment by gomsoup** [comment]
Still exists. it's very malicious module

**Comment by seonggwonyoon** [comment]
> Still exists. it's very malicious module

I agree still exists.
